GET http://localhost:3000/events

###
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "My Event",
  "description": "This is a great event",
  "date": "2020-01-01T12:00:00",
  "price": 10.5
}

###
GET http://localhost:3000/events/d36767cd-e73a-40e7-88d1-e7403bec1bec

###
PATCH http://localhost:3000/events/d36767cd-e73a-40e7-88d1-e7403bec1bec
Content-Type: application/json

{
  "name": "My Event Updated",
  "description": "This is a great event",
  "date": "2020-01-01T12:00:00",
  "price": 10.5
}

###
DELETE http://localhost:3000/events/6c2ef089-d8e3-40ed-b3a6-f2f411cc1de2